import { NAME } from './constants';

const PREFIX = NAME + '/';

export const COMPLETED_FETCHING_THESAURUS_RESULTS = PREFIX + 'COMPLETED_FETCHING_THESAURUS_RESULTS';
export const STARTED_FETCHING_THESAURUS_RESULTS = PREFIX + 'STARTED_FETCHING_THESAURUS_RESULTS';

export const COMPLETED_FETCHING_WSPOSLIST = PREFIX + 'COMPLETED_FETCHING_WSPOSLIST';
export const STARTED_FETCHING_WSPOSLIST = PREFIX + 'STARTED_FETCHING_WSPOSLIST';

export const DISPLAY_ADVANCED_SETTINGS = PREFIX + 'DISPLAY_ADVANCED_SETTINGS';
export const HIDE_ADVANCED_SETTINGS = PREFIX + 'HIDE_ADVANCED_SETTINGS';
export const PIN_ADVANCED_SETTINGS = PREFIX + 'PIN_ADVANCED_SETTINGS';
export const UNPIN_ADVANCED_SETTINGS = PREFIX + 'UNPIN_ADVANCED_SETTINGS';

export const RESET_ADVANCED_SETTINGS = PREFIX + 'RESET_ADVANCED_SETTINGS';

export const CHANGE_LEMMA = PREFIX + 'CHANGE_LEMMA';
export const CHANGE_ADVANCED_SETTINGS = PREFIX + 'CHANGE_ADVANCED_SETTINGS';
